services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/postgres
      PORT: 3000
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      PORT: 3001
      API_URL: http://api:3000
    ports:
      - "3000:3001"
    depends_on:
      - api
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
